apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-helm-application
  namespace: argocd
spec:
  project: default
  source:
    # directory: 
    # include: 'deployment.yml,nginx-deployment.yml'
    repoURL: https://github.com/dipakrasal2009/ArgoCD.git
    targetRevision: HEAD
    path: helm/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: myhelmapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
